services:
  - type: web
    name: scrap-management
    runtime: node
    plan: free
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        fromService:
          type: web
          name: scrap-management
          property: url
